config/routes.rb
Rails.application.routes.draw do
  get "/homes/about" => "homes#about", as: "about"
  get 'contacts/index'
  post 'contacts/done'
  post 'contacts/confirm'
  get "search" => "searches#search"
  resources :groups do      
    post "join" => "groups#join"
    delete "disjoin" => "groups#disjoin"
  end
  
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
   resources :customers
  end
  
  scope module: :public do
   root to: 'customers#show'
   resources :customers
   resources :events
  end# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
 has_many :events, dependent: :destroy
 has_many :customers
 has_secure_password
 validates :owner_id, presence: true, uniqueness: true
 validates :name, presence: true
 validates :introduction, presence: true

 def self.looks(search, word)
    if search == "perfect_match"
      @group = Group.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @group= Group.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @group = Group.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @group = Group.where("name LIKE?","%#{word}%")
    else
     @group = Group.all
    end
 end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_customer!

      def new
        @group = Group.new
      end

      def index
        @groups = Group.all
        @groups = Group.page(params[:page])
      end


      def show
        @group = Group.find(params[:id])
        @events = @group.events
        @event = Event.new
      end

      def edit
        @group = Group.find(params[:id])
        if @group.owner_id == current_customer.id
         render "edit"
        else
         redirect_to group_path(@group.id)
        end
      end

      def create
        @group = Group.new(group_params)
        @group.owner_id = current_customer.id
        if @group.save
          current_customer.update(group_id: @group.id)
          redirect_to group_path(@group.id)
        else
          render 'new'
        end
      end

      def update
       @group = Group.find(params[:id])
       @group.customers << current_customer
        if @group.update(group_params)
          redirect_to group_path(@group.id)
        else
          render "edit"
        end
      end

      def join
        @group = Group.find(params[:group_id])
        if @group.password_digest == (params[:group][:password])
          @group.customers << current_customer
          redirect_to group_path(@group.id)
        else
          redirect_to groups_path
        end

      end

        def disjoin
         @group = Group.find(params[:group_id])
         @group.customers.delete(current_customer)
         redirect_to groups_path
        end

        def destroy
          @group = Group.find(params[:id])
          @group.destroy
          redirect_to groups_path
        end


      private

      def group_params
        params.require(:group).permit(:name, :introduction, :password_digest)
      end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<p class="text-lg-center font-2">group edit</p>
　　 <div class="d-flex justify-content-center">
    　 <%= form_with model:@group, url:group_path, method: :patch do |f| %>

            <div class = "mt-5 font-3">
                    <tr>
                      <td>group name</td>
                      <td><%= f.text_field :name, autofocus: true, :size => "30*30" %></td>
                    </tr>
                  </div>

                 <div class = "mt-5 font-3">
                    <tr>
                      <td>group introduction</td>
                      <%= f.text_field :introduction, :size => "26*30" %></td>
                    </tr>
                </div>

         <div class="d-flex justify-content-end mt-5">
            <%= f.submit'update', class:"btn btn-success" %>
         </div>
    　 <% end %>
    　</div>

app/views/groups/index.html.erb
     <h5>グループ一覧<h5>
      <table class="table">
          <thead class="thead-dark">
          <thead>
                <tr>
                  <th>グループ名</th>
                  <th>グループ説明</th>
                </tr>
          </thead>
          <tbody>
            <tr>
                 <% @groups.each do |f| %>
                  <td><%= f.name %></td>
                  <td><%= f.introduction %></td>
                      <% if f.owner_id == current_customer.id %>
                       <td><%= link_to 'edit', edit_group_path(f.id), class: "btn btn-sm btn-success" %></td>
                       <td><%= link_to 'destroy', group_path(f.id), method: :delete,class: "btn btn-sm btn-danger" %></td>
                      <% end %>
                      <td><%= link_to 'detail', group_path(f.id), class: "btn btn-sm btn-primary" %>
          </tr>
                   <% end %>
           <%= paginate @groups %>
          </tbody>
          <% if Group.where(owner_id:current_customer.id).present? %>
            すでにグループを登録済みです
          <% else %>
            グループの作成は<%= link_to"こちら", new_group_path %>
          <% end %>
        </table>

app/views/groups/new.html.erb
         <% if @group.errors.any? %>
            <%= @group.errors.count %>件のエラーが発生しました
            <ul>
              <% @group.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
                  <div class="container mt-4">
          <div class="row">
            <div class="col-md-12 col-lg-6 offset-lg-3">
            <p class="text-center bg-info text-white font-2">グループ作成</p>
             <div class="d-flex justify-content-center">
                <%= form_with model:@group, url:groups_path, method: :post do |f| %>
                     <div class ="mt-5">
                        <h4>group name</h4>
                        <span class="badge badge-info rounded-0">必須</span>
                        <%= f.text_field :name, :size => "60*30" %>
                     </div>
                     <div class ="mt-5">
                        <h4>group introduciton</h4>
                        <span class="badge badge-info rounded-0">必須</span>
                        <%= f.text_area :introduction, :size => "60*60" %>
                     </div>

                      <div class ="mt-5">
                        <h4>password</h4>
                        <span class="badge badge-info rounded-0">必須</span>
                        <%= f.text_area :password_digest, :size => "60*60" %>
                     </div>
                     <div>
                        <%= f.submit'registration',class:"btn btn-success" %>
                     </div>
                <% end %>
             </div>
            </div>
        　</div>
        </div>

app/views/groups/show.html.erb
<h2>Group Detail</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.customers.each do |member| %>
                <%= member.full_name %><br>
              <% end %>
            </td>
          </tr>
            <td>
              <% if @group.owner_id == current_customer.id %>
                <%= link_to '更新', edit_group_path(@group), class: "btn btn-sm btn-success" %>
                <%= link_to '削除', group_path(@group), method: :delete,class: "btn btn-sm btn-danger" %>
                 <%= render partial: 'public/events/form', locals: { event: @event, group: @group} %>
                 <%= render template:"public/events/index" %>
              <% elsif @group.customers.include?(current_customer) %>
                <%= link_to 'Leave this group', group_disjoin_path(@group), method: :delete, class: "btn btn-sm btn-danger" ,data: { confirm: "【確認】グループを退会してもよろしいですか？" } %>
                  <%= render partial: 'public/events/form', locals: { event: @event, group: @group} %>
                  <%= render template:"public/events/index" %>
                 <% else %>
            <%= form_with scope: "group", url:group_join_path(@group) do |form| %>
                 <%= form.password_field :password %>
                <%= form.button 'Join this group', class: "btn btn-sm btn-success",data: { confirm: "【確認】グループに入会しますか？" } %>
              <% end %>
            <% end %>
              
            </td>
           </tr>
          </tbody>