config/routes.rb
Rails.application.routes.draw do
  get "/homes/about" => "homes#about", as: "about"
  get 'contacts/index'
  post 'contacts/done'
  post 'contacts/confirm'
  get "search" => "searches#search"
  resources :groups do      
    post "join" => "groups#join"
    delete "disjoin" => "groups#disjoin"
  end
  
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
   resources :customers
  end
  
  scope module: :public do
   root to: 'customers#show'
   resources :customers
   resources :events
  end# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
     before_action :authenticate_customer!

  def search
    @range = params[:range]

    if @range == "Customer"
      @customers = Customer.looks(params[:search], params[:word])
    else
      @groups = Group.looks(params[:search], params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if customer_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['Group']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<h2>検索結果</h2>

<table class="table table-hover table-inverse">
 
  <% if @range == "Customer" %>
    <tbody>
      <% @customers.each do |f| %>
        <tr>
          <td><%= f.first_name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <tbody>
      <% @groups.each do |f| %>
        <tr>
          <td>
            <%= link_to group_path(f.id) do %>
              <%= f.name %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
 <% end %>
</table>select * from meibo;

app/views/searches/search_result.html.erb
<h2>Results index</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがCustomerの時 -->
  <% if @range == "Customer" %>
    <tbody>
      <% @customers.each do |f| %>
        <tr>
          <td><%= f.full_name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがGroupの時) -->
  
    <tbody>
    
      <% @groups.each do |f| %>
        <tr>
          <td>
          <%= link_to group_path(f.id) do %>
            <%= f.name %>
            
            aaaaa
          <% end %>
          </td>
          
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>